account/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from django.views.generic import TemplateView

from .forms import (UserLoginForm, PwdResetForm, PwdResetConfirmForm)
from . import views

app_name = 'account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='account/login.html',
         form_class=UserLoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='/account/login/'), name='logout'),
    path('register/', views.account_register, name='register'),
    path('activate/<slug:uidb64>/<slug:token>/', views.account_activate, name='activate'),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name="account/password_reset/password_reset_form.html",
                                                                 success_url='password_reset_email_confirm/',
                                                                 email_template_name='account/password_reset/password_reset_email.html',
                                                                 form_class=PwdResetForm), name='pwdreset'),
    path('password_reset_confirm/<uidb64>/<token>', auth_views.PasswordResetConfirmView.as_view(template_name='account/password_reset/password_reset_confirm.html',
                                                                                                success_url='/account/password_reset_complete/',
                                                                                                form_class=PwdResetConfirmForm), name="password_reset_confirm"),
    path('password_reset/password_reset_email_confirm/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_done'),
    path('password_reset_complete/',
         TemplateView.as_view(template_name="account/password_reset/reset_status.html"), name='password_reset_complete'),

    # User dashboard
    path('dashboard/', views.dashboard, name='dashboard'),
    path('profile/edit/', views.edit_details, name='edit_details'),
    path('profile/delete_user/', views.delete_user, name='delete_user'),
    path('profile/delete_confirm/', TemplateView.as_view(template_name='account/dashboard/delete_confirm.html'),
         name='delete_confirmation'),

    # Addresses
    path("addresses/", views.view_address, name="addresses"),
    path("add_address/", views.add_address, name="add_address"),
    path("addresses/edit/<slug:id>/", views.edit_address, name="edit_address"),
    path("addresses/delete/<slug:id>/", views.delete_address, name="delete_address"),
    path("addresses/set_default/<slug:id>/", views.set_default, name="set_default"),

    # Wishlist
    path("wishlist", views.wishlist, name="wishlist"),
    path("wishlist/add_to_wishlist/<int:id>", views.add_to_wishlist, name="add_to_wishlist"),

    # Orders
    path("user_orders/", views.user_orders, name="user_orders"),
]

basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('kategorie/<slug:category_slug>/', views.category_list, name='category_list'),
]

store/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse
from mptt.models import MPTTModel, TreeForeignKey


from django.utils.text import slugify


class Category(MPTTModel):
    """
    Category Table implimented with MPTT.
    """

    name = models.CharField(
        verbose_name=("Category Name"),
        help_text=("Required and unique"),
        max_length=255,
        unique=True,
    )
    slug = models.SlugField(verbose_name=("Category safe URL"), max_length=255, unique=True)
    parent = TreeForeignKey("self", on_delete=models.CASCADE, null=True, blank=True, related_name="children")
    is_active = models.BooleanField(default=True)

    class MPTTMeta:
        order_insertion_by = ["name"]

    class Meta:
        verbose_name = ("Category")
        verbose_name_plural = ("Categories")

    def get_absolute_url(self):
        return reverse("store:category_list", args=[self.slug])

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


class ProductType(models.Model):
    """
    ProductType Table will provide a list of the different types
    of products that are for sale.
    """

    name = models.CharField(verbose_name=("Product Name"), help_text=("Required"), max_length=255, unique=True)
    is_active = models.BooleanField(default=True)

    class Meta:
        verbose_name = ("Product Type")
        verbose_name_plural = ("Product Types")

    def __str__(self):
        return self.name


class ProductSpecification(models.Model):
    """
    The Product Specification Table contains product
    specifiction or features for the product types.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    name = models.CharField(verbose_name=("Name"), help_text=("Required"), max_length=255)

    class Meta:
        verbose_name = ("Product Specification")
        verbose_name_plural = ("Product Specifications")

    def __str__(self):
        return self.name


class Product(models.Model):
    """
    The Product table contining all product items.
    """

    product_type = models.ForeignKey(ProductType, on_delete=models.RESTRICT)
    category = models.ForeignKey(Category, on_delete=models.RESTRICT)
    title = models.CharField(
        verbose_name=("title"),
        help_text=("Required"),
        max_length=255,
    )
    description = models.TextField(verbose_name=("description"), help_text=("Not Required"), blank=True)
    slug = models.SlugField(max_length=255)
    regular_price = models.DecimalField(
        verbose_name=("Regular price"),
        help_text=("Maximum 9999"),
        error_messages={
            "name": {
                "max_length": ("The price must be between 0 and 9999."),
            },
        },
        max_digits=4,
        decimal_places=0,
    )
    discount_price = models.DecimalField(
        verbose_name=("Discount price"),
        help_text=("Maximum 9999"),
        error_messages={
            "name": {
                "max_length": ("The price must be between 0 and 9999."),
            },
        },
        max_digits=4,
        decimal_places=0,
    )
    is_active = models.BooleanField(
        verbose_name=("Product visibility"),
        help_text=("Change product visibility"),
        default=True,
    )
    on_homepage = models.BooleanField(
        verbose_name=("Zobrazit na domovské stránce"),
        default=True,
    )
    created_at = models.DateTimeField(("Created at"), auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(("Updated at"), auto_now=True)
    users_wishlist = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name="user_wishlist", blank=True)

    class Meta:
        ordering = ("-created_at",)
        verbose_name = ("Product")
        verbose_name_plural = ("Products")

    def get_absolute_url(self):
        return reverse("store:product_detail", args=[self.slug])

    def __str__(self):
        return self.title


class ProductSpecificationValue(models.Model):
    """
    The Product Specification Value table holds each of the
    products individual specification or bespoke features.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    specification = models.ForeignKey(ProductSpecification, on_delete=models.RESTRICT)
    value = models.CharField(
        verbose_name=("value"),
        help_text=("Product specification value (maximum of 255 words"),
        max_length=255,
    )

    class Meta:
        verbose_name = ("Product Specification Value")
        verbose_name_plural = ("Product Specification Values")

    def __str__(self):
        return self.value


class ProductImage(models.Model):
    """
    The Product Image table.
    """

    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_image")
    image = models.ImageField(
        verbose_name=("image"),
        help_text=("Upload a product image"),
        upload_to="images/",
        default="images/default.png",
    )
    alt_text = models.CharField(
        verbose_name=("Alternative text"),
        help_text=("Please add alternative text"),
        default="Responsive image",
        max_length=255,
        null=True,
        blank=True,
    )
    is_feature = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name = ("Product Image")
        verbose_name_plural = ("Product Images")

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


def product_all(request):
    products = Product.objects.prefetch_related("product_image").filter(is_active=True)
    return render(request, 'store/index.html', {'products': products})


def category_list(request, category_slug=None):
    category = get_object_or_404(Category, slug=category_slug)
    # products = Product.objects.filter(category=category)
    products = Product.objects.filter(
        category__in=Category.objects.get(slug=category_slug).get_descendants(include_self=True)
    )
    return render(request, "store/category.html", {"category": category, "products": products})


def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug, is_active=True)
    is_in_wishlist = product.users_wishlist.filter(id=request.user.id).exists()
    return render(request, 'store/single.html', {'product': product, 'is_in_wishlist': is_in_wishlist})

templates/store/category.html
{% extends "../base.html" %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12 pb-3">
    <h1 class="h2">{{category.name|title}}</h1>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="album">
      {% if not products %}
      <div class="col-12">Aktuálně nejsou žádné produkty k dispozici</div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        <div class="col">
          <div class="card shadow-sm">
            {% for image in product.product_image.all %}
            {% if image.is_feature%}
            <a href="{{ product.get_absolute_url }}">
              <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.alt_text }}">
            </a>
            {% endif %}
            {% endfor %}
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none" href="{{ product.get_absolute_url }}">{{ product.title }}</a>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="fw-bold">{{ product.regular_price }} Kč</div>
              </div>
            </div>
          </div>
        </div>
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>

{% endblock %}

templates/store/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}*{% endblock %}
{% block content %}

{% comment %} <section class="text-center container">
  <div class="row py-lg-3">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="h1 fw-bold">Nadpis</h1>
      <p class="lead text-muted sansserif">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget
        porttitor ex. In hac habitasse platea dictumst. Sed ut sapien et lectus molestie efficitur sed sed
        libero. Vestibulum quis bibendum felis. Morbi semper metus sit amet felis faucibus porta. Cras venenatis
        augue eu imperdiet dignissim. Suspendisse sed tempus neque. Vivamus quis sodales nunc, ut ultrices arcu.
        Aliquam erat volutpat. Phasellus vitae augue semper, rutrum nulla sed, sollicitudin justo. In eu
        tristique nibh, ac aliquam odio. Phasellus blandit dui ut libero rutrum, nec bibendum quam bibendum.
        Aliquam tellus est, hendrerit eget fringilla vitae, efficitur vel nunc.</p>
      <p>
        <a href="#" class="btn btn-primary my-2">Tlačítko</a>
      </p>
    </div>
  </div>
</section> {% endcomment %}
<div id="react-mount-point"></div>
<div class="container">
  <div class="row">
    <div class="album pt-5">
      <div class="col-12 pb-3">
        <h1 class="h3">Nejpopulárnější produkty</h1>
      </div>
      {% if not products %}
      <div class="col-12">Aktuálně nejsou žádné produkty k dispozici</div>
      {% else %}
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-5 g-3">
        {% for product in products %}
        {% if product.on_homepage %}
        <div class="col">
          <div class="card shadow-sm">
            {% for image in product.product_image.all %}
            {% if image.is_feature %}
            <a href="{{ product.get_absolute_url }}">
              <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.alt_text }}">
            </a>
            {% endif %}
            {% endfor %}
            <div class="card-body">
              <p class="card-text">
                <a class="text-dark text-decoration-none"
                  href="{{ product.get_absolute_url }}">{{ product.title|slice:":50" }}</a>
              </p>
              <div class="fw-bold">{{ product.regular_price }} Kč</div>
            </div>
          </div>
        </div>
        {% endif %}
        {% endfor %}
      </div>
      {% endif %}
    </div>
  </div>
</div>


{% comment %} 
<div id="react-mount-point"></div>
<script src="https://unpkg.com/react/umd/react.development.js"></script>
<script src="https://unpkg.com/react-dom/umd/react-dom.development.js"></script>
<script>
  ReactDOM.render(
    React.createElement(
      'div',
      null,
      'Hello, World!'
    ),
    document.getElementById('react-mount-point')
  );
</script> {% endcomment %}
<script src="https://unpkg.com/react/umd/react.production.min.js"></script>
<script src="https://unpkg.com/react-dom/umd/react-dom.production.min.js"></script>
<script>
  const TEXTS = [
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla at turpis vitae ante dictum facilisis eu et mi. Ut convallis fringilla viverra. Sed pellentesque eros id dolor scelerisque viverra. Pellentesque eros tellus, tincidunt sed varius in, pretium eu nisl. Quisque egestas ac libero et tincidunt. In placerat, enim non dictum porta, quam metus rhoncus dolor, eu gravida magna tellus id diam. Nullam cursus tortor faucibus purus imperdiet, quis ornare dolor vestibulum.',
    'Proin venenatis lobortis mi, vel sodales eros tempus eget. Proin imperdiet ex vitae urna iaculis fringilla. Quisque tempus ornare feugiat. Nunc ac purus at quam tincidunt hendrerit a vehicula nibh. Curabitur tincidunt suscipit suscipit. Vestibulum viverra blandit quam quis convallis. Vestibulum dapibus justo eget nulla iaculis ultricies. Donec lorem lacus, hendrerit a felis eget, placerat porttitor metus.',
    'Duis a eleifend dolor. Sed quis urna elit. Fusce bibendum commodo lobortis. Mauris sagittis non purus et maximus. Proin eget efficitur mi, sed varius tortor. Aenean porta auctor velit nec tempor. Vestibulum mattis nisi at mi porta porta.',
  ];

  class AnimatedText extends React.Component {
    constructor(props) {
      super(props);
      this.state = {
        textIndex: 0,
        isFading: false,
      };
    }

    componentDidMount() {
      this.intervalId = setInterval(() => {
        this.setState({
          isFading: true,
        });
        setTimeout(() => {
          this.setState(prevState => ({
            textIndex: (prevState.textIndex + 1) % TEXTS.length,
            isFading: false,
          }));
        }, 500);
      }, 20000);
    }

    componentWillUnmount() {
      clearInterval(this.intervalId);
    }

    render() {
      const { isFading, textIndex } = this.state;
      const currentText = TEXTS[textIndex];
      const className = isFading ? 'fade-out' : 'fade-in';
      return React.createElement('p', { className: 'lead text-muted sansserif ' + className }, currentText);
    }
  }

  const section = React.createElement(
    'section',
    { className: 'text-center container' },
    React.createElement(
      'div',
      { className: 'row py-lg-3' },
      React.createElement(
        'div',
        { className: 'col-lg-6 col-md-8 mx-auto' },
        React.createElement(
          'h1',
          { className: 'h1 fw-bold' },
          'Nadpis'
        ),
        React.createElement(
          AnimatedText,
          null
        ),
        React.createElement(
          'p',
          null,
          React.createElement(
            'a',
            { href: '#', className: 'btn btn-primary my-2' },
            'Tlačítko'
          )
        )
      )
    )
  );

  ReactDOM.render(section, document.getElementById('react-mount-point'));
</script>

<style>
  .fade-in {
    opacity: 1;
    transition: opacity 0.5s ease-in-out;
  }

  .fade-out {
    opacity: 0;
    transition: opacity 0.5s ease-in-out;
  }
  
  .lead {
    font-size: 1.25rem;
    font-weight: 300;
  }
  
  .text-muted {
    color: #6c757d;
  }
</style>

{% endblock %}

templates/store/single.html
{% extends "../base.html" %}
{% load static %}
{% block stylesheet %}{% static 'store/css/single.css' %}{% endblock %}
{% block title %}
{% if product %}{{ product.title }}{% else %}Product{% endif %}
{% endblock %}
{% block content %}

<div class="container">
  <div class="row g-3">
    <div class="col-md-5 px-3 col-lg-5 order-md-last p-0 order-1">
      <div class="d-grid gap-2">
        <h1 class="mb-0 h4">Popis</h1>
        <p>{{ product.description }}</p>
        <div class="d-flex d-flex-inline justify-content-between">
          <div><span class="h3">{{ product.regular_price }} Kč</span>
            <p class="text-muted">včetně DPH</p>
          </div>
          <div>
            <label for="select">Počet</label>
            <select id="select" class="h6 store-select-dropdown">
              <option value="1">1</option>
              <option value="2">2</option>
              <option value="3">3</option>
              <option value="4">4</option>
            </select>
          </div>
        </div>
        <hr>
        <button type="button" id="add-button" value="{{product.id}}" class="btn btn-success fw500">
          Přidat do košíku
        </button>
      </div>
    </div>
    <div class="col-md-7 col-lg-7 p-0">
      <div class="card mb-3 border-0">
        <div class="row g-0">
          <div class="col-md-12">
            <div class="card-body p-1">
              <div class="col-12 pb-3 d-flex d-flex-inline justify-content-between">
                <h1 class="h2">{{ product.title }}</h1>
                {% if user.is_authenticated %}
                {% if is_in_wishlist %}
                <a href="{% url 'account:add_to_wishlist' product.id %}" class="link-danger" role="button">
                  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                    class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                    <path
                      d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z" />
                  </svg>
                </a>
                {% else %}
                <a href="{% url 'account:add_to_wishlist' product.id %}" class="link-dark" role="button">
                  <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor"
                    class="bi bi-suit-heart" viewBox="0 0 16 16">
                    <path
                      d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z" />
                  </svg>
                </a>
                {% endif %}
                {% endif %}
              </div>
              <div class="bg-light">
                {% for image in product.product_image.all %}
                {% if image.is_feature %}
                <img class="img-fluid mx-auto d-block" width="200px" src="{{ image.image.url }}"
                  alt="{{ image.alt_text }}">
                {% else %}
                <img class="img-fluid d-block-inline pt-3" width="100px" src="{{ image.image.url }}"
                  alt="{{ image.alt_text }}">
                {% endif %}
                {% endfor %}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).on('click', '#add-button', function (e) {
    e.preventDefault();

    $.ajax({
      type: 'POST',
      url: '{% url "basket:basket_add" %}',
      data: {
        productid: $('#add-button').val(),
        productqty: $('#select option:selected').text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: 'post'
      },

      success: function (json) {
        document.getElementById("basket-qty").innerHTML = json.qty
      },
      error: function (xhr, errmsg, err) {}
    });
  })
</script>


{% endblock %}