basket/urls.py
from django.urls import path

from . import views

app_name = 'basket'

urlpatterns = [
    path('', views.basket_summary, name='basket_summary'),
    path('add/', views.basket_add, name='basket_add'),
    path('delete/', views.basket_delete, name='basket_delete'),
    path('update/', views.basket_update, name='basket_update'),
]

checkout/urls.py
from django.urls import include, path

from . import views

app_name = "checkout"

urlpatterns = [
    path("delivery_choices/", views.deliverychoices, name="delivery_choices"),
    path("basket_update_delivery/", views.basket_update_delivery, name="basket_update_delivery"),
    path("delivery_address/", views.delivery_address, name="delivery_address"),
    path("payment_selection/", views.payment_selection, name="payment_selection"),
    path("payment_complete/", views.payment_complete, name="payment_complete"),
    path("payment_successful/", views.payment_successful, name="payment_successful"),
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('checkout/', include('checkout.urls', namespace='checkout')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
    path('orders/', include('orders.urls', namespace='orders')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='store_home'),
    path('<slug:slug>', views.product_detail, name='product_detail'),
    path('kategorie/<slug:category_slug>/', views.category_list, name='category_list'),
]

basket/views.py
from django.http import JsonResponse
from django.shortcuts import get_object_or_404, render

from store.models import Product

from .basket import Basket


def basket_summary(request):
    basket = Basket(request)
    return render(request, 'basket/summary.html', {'basket': basket})


def basket_add(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)

        basketqty = basket.__len__()
        response = JsonResponse({'qty': basketqty})
        return response


def basket_delete(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.delete(product=product_id)

        basketqty = basket.__len__()
        baskettotal = basket.get_total_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': baskettotal})
        return response


def basket_update(request):
    basket = Basket(request)
    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)

        basketqty = basket.__len__()
        basketsubtotal = basket.get_subtotal_price()
        response = JsonResponse({'qty': basketqty, 'subtotal': basketsubtotal})
        return response

templates/basket/summary.html
{% extends "../base.html" %}
{% load static %}
{% block title %}Košík{% endblock %}
{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Košík</h1>
  </div>
  <hr />
</div>
<div class="container">
  <div class="row g-3" id="basketSection">
    {% if basket|length == 0 %}
    <div class="text-center pt-5 my-5">
      <h1 class="col-12 h3">Košík je prázdný</h1>
      <p>
        <a href="{% url 'store:store_home'%}" class="btn btn-primary my-2">Pokračovat v nákupu</a>
      </p>
    </div>
    {% else %}
      <div class="col-12 bg-light p-3 d-flex justify-content-between" id="basketInfo">
        <div class="d-flex d-flex-inline">
          <div class="pe-3">Objednávka</div>
        </div>
        <div class="text-end">
          <div class="">Celkem: <div id="subtotal" class="d-inline-flex fw-bold h5">{{basket.get_subtotal_price}}
            </div><span class="fw-bold h5"> Kč</span></div>
        </div>
      </div>
      <div class="col-md-5 col-lg-4 order-md-last p-0 order-3" id="basketCheckoutButton">
        <div class="d-grid gap-2 ">
          <a role="button" href="{% url 'checkout:delivery_choices' %}" class="btn btn-success fw-bold" type="button">Přejít
            k pokladně</a>
          {% comment %} <button class="btn btn-light" type="button">Save for later</button> {% endcomment %}
        </div>
      </div>
      <div class="col-md-7 col-lg-8 p-0" id="basketProducts">
        {% for item in basket %}
        {% with product=item.product %}
        <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
          <div class="row g-0">
            <div class="col-md-2 d-block d-md-none">
              {% for image in product.product_image.all %}
                  {% if image.is_feature %}
                      <a href="{{ product.get_absolute_url }}">
                          <img style="width:80px;" class="img-fluid" src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                      </a>
                  {% endif %}
              {% endfor %}
          </div>
          
          <div class="col-md-2 d-none d-md-block">
              {% for image in product.product_image.all %}
                  {% if image.is_feature %}
                      <a href="{{ product.get_absolute_url }}">
                          <img class="img-fluid" src="{{ image.image.url }}" alt="{{ image.alt_text }}">
                      </a>
                  {% endif %}
              {% endfor %}
          </div>
            <div class="col-md-10 ps-md-3">
              <div class="card-body p-1">
                <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                  <p class="card-text pb-3">{{product.title}}</p>
                </a>
                <label for="select">Počet</label>
                <select id="select{{product.id}}" style="width:50px;height:32px;">
                  <option value="" selected disabled hidden>{{item.qty}}</option>
                  <option value="">1</option>
                  <option value="">2</option>
                  <option value="">3</option>
                  <option value="">4</option>
                </select>
                <button type="button" id="update-button" data-index="{{product.id}}"
                  class="btn btn-outline-success btn-sm update-button" style="margin-bottom:2px">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                    class="bi bi-arrow-repeat" viewBox="0 0 16 16">
                    <path
                      d="M11.534 7h3.932a.25.25 0 0 1 .192.41l-1.966 2.36a.25.25 0 0 1-.384 0l-1.966-2.36a.25.25 0 0 1 .192-.41zm-11 2h3.932a.25.25 0 0 0 .192-.41L2.692 6.23a.25.25 0 0 0-.384 0L.342 8.59A.25.25 0 0 0 .534 9z">
                    </path>
                    <path fill-rule="evenodd"
                      d="M8 3c-1.552 0-2.94.707-3.857 1.818a.5.5 0 1 1-.771-.636A6.002 6.002 0 0 1 13.917 7H12.9A5.002 5.002 0 0 0 8 3zM3.1 9a5.002 5.002 0 0 0 8.757 2.182.5.5 0 1 1 .771.636A6.002 6.002 0 0 1 2.083 9H3.1z">
                    </path>
                  </svg>
                </button>
                <button type="button" id="delete-button" data-index="{{product.id}}"
                  class="btn btn-outline-danger btn-sm delete-button" style="margin-bottom:2px">
                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash"
                    viewBox="0 0 16 16">
                    <path
                      d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z">
                    </path>
                    <path fill-rule="evenodd"
                      d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z">
                    </path>
                  </svg>
                </button>
                <p class="card-text pb-3">Cena za kus: {{product.regular_price}} Kč</p>
              </div>
            </div>
          </div>
        </div>
        {% endwith %}
        {% endfor %}
      </div>
    {% endif %}
  </div>
</div>

<script>
  // Delete Item
  $(document).on("click", ".delete-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_delete" %}',
      data: {
        productid: $(this).data("index"),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {
        $('.product-item[data-index="' + prodid + '"]').remove();

        if (json.qty == 0) {
          document.getElementById("basket-qty").innerHTML = json.qty;

          // Delete basket components
          const basketInfo = document.getElementById("basketInfo");
          const basketCheckoutButton = document.getElementById("basketCheckoutButton");
          const basketProducts = document.getElementById("basketProducts");
          basketInfo.remove();
          basketCheckoutButton.remove();
          basketProducts.remove();

          // Create a new div, h1, p and a element
          const div = document.createElement('div');
          div.classList.add('text-center', 'pt-5', 'my-5');
          const h1 = document.createElement('h1');
          h1.classList.add('col-12', 'h3');
          h1.textContent = 'Košík je prázdný';
          const p = document.createElement('p');
          const a = document.createElement('a');
          a.classList.add('btn', 'btn-primary', 'my-2');
          a.href = '{% url "store:store_home"%}';
          a.textContent = 'Pokračovat v nákupu';

          // Append the a to p, append h1 and p to div and div to basketSection
          p.appendChild(a);
          div.appendChild(h1);
          div.appendChild(p);
          document.getElementById("basketSection").appendChild(div);
        } else {
          total = (parseFloat(json.subtotal) + 99);
          subtotal = json.subtotal
          document.getElementById("subtotal").innerHTML = subtotal;
          document.getElementById("total").innerHTML = total;
        }
      },
      error: function (xhr, errmsg, err) {},
    });
  });

  // Update Item
  $(document).on("click", ".update-button", function (e) {
    e.preventDefault();
    var prodid = $(this).data("index");
    $.ajax({
      type: "POST",
      url: '{% url "basket:basket_update" %}',
      data: {
        productid: $(this).data("index"),
        productqty: $("#select" + prodid + " option:selected").text(),
        csrfmiddlewaretoken: "{{csrf_token}}",
        action: "post",
      },
      success: function (json) {

        total = (parseFloat(json.subtotal) + 99);
        document.getElementById("basket-qty").innerHTML = json.qty;
        document.getElementById("subtotal").innerHTML = json.subtotal;
        document.getElementById("total").innerHTML = total;
      },
      error: function (xhr, errmsg, err) {},
    });
  });
</script>

{% endblock %}